-- instance private
print("f.a = ", f.a)
print("f.b = ", f.b)
print("f.c = ", f.c)
print("f.d = ", f.d)
print("f.e = ", f.e)
print("f.f = ", f.f)
print("f.g = ", f.g)
print("f.h = ", f.h)
print("f.i = ", f.i)
print("f.j = ", f.j)
-- print("f.k = ", f.k)

-- instance public
print("f.pa = ", f.pa)
print("f.pb = ", f.pb)
print("f.pc = ", f.pc)
print("f.pd = ", f.pd)
print("f.pe = ", f.pe)
print("f.pf = ", f.pf)
print("f.pg = ", f.pg)
print("f.ph = ", f.ph)
print("f.pi = ", f.pi)
print("f.pj = ", f.pj)
-- print("f.pk = ", f.pk)

-- instance public static
print("f.psa = ", f.psa)
print("f.psb = ", f.psb)
print("f.psc = ", f.psc)
print("f.psd = ", f.psd)
print("f.pse = ", f.pse)
print("f.psf = ", f.psf)
print("f.psg = ", f.psg)
print("f.psh = ", f.psh)
print("f.psi = ", f.psi)
print("f.psj = ", f.psj)
-- print("f.psk = ", f.psk)

-- instance private static
print("f.sa = ", f.sa)
print("f.sb = ", f.sb)
print("f.sc = ", f.sc)
print("f.sd = ", f.sd)
print("f.se = ", f.se)
print("f.sf = ", f.sf)
print("f.sg = ", f.sg)
print("f.sh = ", f.sh)
print("f.si = ", f.si)
print("f.sj = ", f.sj)
-- print("f.sk = ", f.sk)

-- instance public static final
print("f.fsa = ", f.fsa)
print("f.fsb = ", f.fsb)
print("f.fsc = ", f.fsc)
print("f.fsd = ", f.fsd)
print("f.fse = ", f.fse)
print("f.fsf = ", f.fsf)
print("f.fsg = ", f.fsg)
print("f.fsh = ", f.fsh)
print("f.fsi = ", f.fsi)
print("f.fsj = ", f.fsj)
-- print("f.fsk = ", f.fsk)

-- class private
-- print("cf.a = ", cf.a)
-- print("cf.b = ", cf.b)
-- print("cf.c = ", cf.c)
-- print("cf.d = ", cf.d)
-- print("cf.e = ", cf.e)
-- print("cf.f = ", cf.f)
-- print("cf.g = ", cf.g)
-- print("cf.h = ", cf.h)
-- print("cf.i = ", cf.i)
-- print("cf.j = ", cf.j)
-- print("cf.k = ", cf.k)

-- class public
-- print("cf.pa = ", cf.pa)
-- print("cf.pb = ", cf.pb)
-- print("cf.pc = ", cf.pc)
-- print("cf.pd = ", cf.pd)
-- print("cf.pe = ", cf.pe)
-- print("cf.pf = ", cf.pf)
-- print("cf.pg = ", cf.pg)
-- print("cf.ph = ", cf.ph)
-- print("cf.pi = ", cf.pi)
-- print("cf.pj = ", cf.pj)
-- print("cf.pk = ", cf.pk)

-- class public static
print("cf.psa = ", cf.psa)
print("cf.psb = ", cf.psb)
print("cf.psc = ", cf.psc)
print("cf.psd = ", cf.psd)
print("cf.pse = ", cf.pse)
print("cf.psf = ", cf.psf)
print("cf.psg = ", cf.psg)
print("cf.psh = ", cf.psh)
print("cf.psi = ", cf.psi)
print("cf.psj = ", cf.psj)
-- print("cf.psk = ", cf.psk)

-- class private static
print("cf.sa = ", cf.sa)
print("cf.sb = ", cf.sb)
print("cf.sc = ", cf.sc)
print("cf.sd = ", cf.sd)
print("cf.se = ", cf.se)
print("cf.sf = ", cf.sf)
print("cf.sg = ", cf.sg)
print("cf.sh = ", cf.sh)
print("cf.si = ", cf.si)
print("cf.sj = ", cf.sj)
-- print("cf.sk = ", cf.sk)

-- class public static final
print("cf.fsa = ", cf.fsa)
print("cf.fsb = ", cf.fsb)
print("cf.fsc = ", cf.fsc)
print("cf.fsd = ", cf.fsd)
print("cf.fse = ", cf.fse)
print("cf.fsf = ", cf.fsf)
print("cf.fsg = ", cf.fsg)
print("cf.fsh = ", cf.fsh)
print("cf.fsi = ", cf.fsi)
print("cf.fsj = ", cf.fsj)
-- print("cf.fsk = ", cf.fsk)