#ifndef LUA_JAVA_COMPATIBLE_LUA53_HEADER
#define LUA_JAVA_COMPATIBLE_LUA53_HEADER

#include "compatible_lua52.h"
#include "compatible_lua53.h"

#ifdef LUAJAVA_ENABLE_METHOD_RESUME_LUA_52
#undef LUAJAVA_ENABLE_METHOD_RESUME_LUA_52
#endif
#define LUAJAVA_ENABLE_METHOD_RESUME_LUA_54

#endif  // LUA_JAVA_COMPATIBLE_LUA53_HEADER


