name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: make
      run: make
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: luajava-dynamic-libraries-linux
        path: "${{ github.workspace }}/build/outputs"
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        path: "${{ github.workspace }}/build/outputs"
