name: C/C++ CI For Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Prepare VS Shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: make
      run: make COMMAND=.\gradlew
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: luajava-dynamic-libraries-windows
        path: "${{ github.workspace }}/build/outputs"
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        path: "${{ github.workspace }}/build/outputs"
