name: Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Linux - Make
      if: runner.os == 'Linux'
      run: make testAll
      
    - name: macOS - Make
      if: runner.os == 'macOS'
      run: make COMMAND="MACOSX_DEPLOYMENT_TARGET=12.0 ./gradlew" testAll
      
    - name: Windows - Prepare VS Shell
      if: runner.os == 'Windows'
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: Windows - Make
      if: runner.os == 'Windows'
      run: make COMMAND=.\gradlew testAll
